### ISSUE TITLE
[Bug] Dropdown UI 오브젝트가 인스펙터 창에 참조가 되지 않는 오류

### ISSUE THREAD

**Issue by KimYonai** [dhghgh189/Unity-TeamProject-TARZ#16]
## 1. 버그 개요
- 드롭다운 UI 오브젝트가 SettingsPanel 스크립트 컴포넌트의 인스펙터 창에 참조가 되지 않는 오류 발생

## 2. 버그 발생 일자
- 2024.12.20(금) 19:11

## 4. 예상되는 문제
- 유사한 사유를 검색해봤지만 나오지 않아 어떠한 문제로 발생하는지 예상 불가

## 5. 필요한 조치
- 다른 UI 오브젝트로는 원활하게 진행 가능
- Unity의 버전 오류일 시, 다른 UI 오브젝트로 작업 필요
- Dropdown 오브젝트가 필요하다고 판단되면 멘토링 및 피드백 요청 예정

## 6. 현재 사용 중인 OS 및 툴 (버전 기재 필수!)
- OS : Window 11
- Unity 버전 : 2022.3.54f1

**Comment by februarywind** [comment]
TMP_Dropdown이 따로 있네요

**Comment by KimYonai** [comment]
위의 방법대로 해결했습니다. 감사합니다!
